### ISSUE TITLE
App requiring root access

### ISSUE THREAD

**Issue by Anyon3** [pentoo/genmenu#1]
Hi,

For the app which require the root access, after entering the root password, a second prompt root will appear. After entering the root password for the second time, the app won't exec (as if it was interrupted) or sometime will close the terminal.

App generated for xfce4 (-x)

After some test, this issue could be related to sudo (line 280) if the user doesn't have enough privilege or hasn't any (sudoers)

**Comment by ZeroChaos-** [comment]
I'm not sure what you are trying to say here, are you saying the menus fail when your user isn't in sudoers?

**Comment by Anyon3** [comment]
Yes that's right, after a merge of sudo / setting sudoers for the target user, the menu work fine.
It wasn't a smart idea to avoid sudo on my system anyway, maybe you could just add something in the script checking if sudo is installed, if not, displaying a message to warn / inform that sudo is missing on the system.

I close the issue since this isn't one. Thanks for your time and sry for this wrong alert

**Comment by ZeroChaos-** [comment]
I added a little warning to make sure your user is in the wheel group.  thanks for the report
