### ISSUE TITLE
collisions genmenu <-> nmap

### ISSUE THREAD

**Issue by Anyon3** [pentoo/genmenu#2]
> > > > Failed to install app-admin/genmenu-9999, Log file:
> > > > 
> > > >  '/var/tmp/portage/app-admin/genmenu-9999/temp/build.log'
> - Messages for package app-admin/genmenu-9999:
> 
> ....................
> - 
> - Detected file collision(s):
> - 
> -    /usr/share/pixmaps/nmap-logo-64.png
> - 
> - Searching all installed packages for file collisions...
> - 
> - Press Ctrl-C to Stop
> - 
> - net-analyzer/nmap-7.12:0::gentoo
> -    /usr/share/pixmaps/nmap-logo-64.png

The merge will work after deleting the png file

I merged genmenu first, then trying to merge nmap : I got this error so I unmerged genmenu and nmap successed. I tried to merge again genmenu and the error appear again (the one displayed on this post).

**Comment by ZeroChaos-** [comment]
odd, I also have nmap 7.12 installed and it doesn't ship that png....

**Comment by ZeroChaos-** [comment]
ahh, it's dependant on the zenmap use flag.  thanks, I'll check it out.

**Comment by ZeroChaos-** [comment]
https://github.com/pentoo/genmenu/commit/e6114d1262b9e039d39d00c27a0641f1ea56d5f4

thanks for the report

**Comment by Anyon3** [comment]
Glad to help and thanks for the fix
